# Generated by Django 3.1.7 on 2021-03-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField(verbose_name='Courier ID')),
                ('courier_type', models.CharField(max_length=8, verbose_name='Courier type')),
                ('regions', models.JSONField(verbose_name='Regions')),
                ('working_hours', models.JSONField(verbose_name='Working hours')),
                ('rating', models.FloatField(default=0, null=True, verbose_name='Rating')),
                ('earnings', models.IntegerField(default=0, null=True, verbose_name='Earnings')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Order ID')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('region', models.IntegerField(verbose_name='Region')),
                ('delivery_hours', models.JSONField(verbose_name='Delivery hours')),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courier', verbose_name='Order assigner')),
            ],
        ),
    ]
