# Generated by Django 3.1.7 on 2021-03-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210318_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='completed_delivery',
            field=models.IntegerField(default=-1, verbose_name='Completed delivery'),
        ),
    ]
